package com.zzjdyf.common.constant;

public interface JmsConstant {
	
	String CONNECTION_FACTORY_NAME_OMS = "OMS_CONNECTION_FACTORY";
	
	String CONNECTION_FACTORY_NAME_PLAT = "PLAT_CONNECTION_FACTORY";
	
	String LISTENER_FACTORY_NAME_OMS_QUEUE = "omsQueueFactory";
	
	String LISTENER_FACTORY_NAME_OMS_TOPIC = "omsTopicFactory";
	
	String LISTENER_FACTORY_NAME_PLAT_QUEUE = "platQueueFactory";
	
	String LISTENER_FACTORY_NAME_PLAT_TOPIC = "platTopicFactory";
	
	String JMS_TEMPLATE_OMS = "OMS_TEMPLATE";
	
	String JMS_TEMPLATE_PLAT = "PLAT_TEMPLATE";
	
	String JMS_MESSAGE_TEMPLATE_OMS = "OMS_MESSAGE_TEMPALTE";
	
	String JMS_MESSAGE_TEMPLATE_PLAT = "PLAT_MESSAGE_TEMPLATE";
	
	String MESSAGE_CONVERTER_NAME = "JMS_CONVERTER";
}
